// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {
		int n = Integer.parseInt(args[0]);
		double test;
		int countAbove = 0;
		int countBelow = 0;

		for (int i = 0; i < n; i++) {
			test = Math.random();
			if (test > 0.5) {
				countAbove++;
			} else {
				countBelow++;
			}
		}

		System.out.println("> 0.5: " + countAbove + " times");
		System.out.println("<= 0.5: " + countBelow + " times");
		if (countAbove == 0 || countBelow == 0) {
		} else {
			System.out.println("Ratio: " + countAbove / (double) countBelow);
		}

	}
}
